services:
  site:
    image: wlcamargo/app-data-hackers 
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == worker]
    ports:
      - "8003:80"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
